@API = http://localhost:4000/api

### CRETE CARTS
POST {{API}}/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjU1Mzc3ZjlhNzc3NzliY2QwOTU1ZSIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5jb2RlckBjb2Rlci5jb20iLCJpYXQiOjE3MTE0MTI2NjIsImV4cCI6MTcxNjU5NjY2Mn0.7aoP3MPVAustQIoIYtIdZbFbwiZFEJaKSpp_Q_o-rYY

### CART
GET {{API}}/carts/660215fac1e18962e973a6b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjU1Mzc3ZjlhNzc3NzliY2QwOTU1ZSIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5jb2RlckBjb2Rlci5jb20iLCJpYXQiOjE3MTE0MTI2NjIsImV4cCI6MTcxNjU5NjY2Mn0.7aoP3MPVAustQIoIYtIdZbFbwiZFEJaKSpp_Q_o-rYY

### ADD PRODUCT
PATCH {{API}}/carts/660215fac1e18962e973a6b5/products/65b54674647153e428f4b948
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjU1Mzc3ZjlhNzc3NzliY2QwOTU1ZSIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5jb2RlckBjb2Rlci5jb20iLCJpYXQiOjE3MTE0MTI2NjIsImV4cCI6MTcxNjU5NjY2Mn0.7aoP3MPVAustQIoIYtIdZbFbwiZFEJaKSpp_Q_o-rYY

### REMOVE PRODUCT FROM CART
DELETE {{API}}/carts/660215fac1e18962e973a6b5/products/6602101ae225a35231da32a0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjU1Mzc3ZjlhNzc3NzliY2QwOTU1ZSIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5jb2RlckBjb2Rlci5jb20iLCJpYXQiOjE3MTE0MTI2NjIsImV4cCI6MTcxNjU5NjY2Mn0.7aoP3MPVAustQIoIYtIdZbFbwiZFEJaKSpp_Q_o-rYY

### REMOVE ALL PRODUCTS FROM CART
DELETE {{API}}/carts/660215fac1e18962e973a6b5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjU1Mzc3ZjlhNzc3NzliY2QwOTU1ZSIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5jb2RlckBjb2Rlci5jb20iLCJpYXQiOjE3MTE0MTI2NjIsImV4cCI6MTcxNjU5NjY2Mn0.7aoP3MPVAustQIoIYtIdZbFbwiZFEJaKSpp_Q_o-rYY

### CREATE TICKET
PATCH {{API}}/carts/660215fac1e18962e973a6b5/purchase
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1YjU1Mzc3ZjlhNzc3NzliY2QwOTU1ZSIsInJvbGUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5jb2RlckBjb2Rlci5jb20iLCJpYXQiOjE3MTE0MTI2NjIsImV4cCI6MTcxNjU5NjY2Mn0.7aoP3MPVAustQIoIYtIdZbFbwiZFEJaKSpp_Q_o-rYY
