@API = http://localhost:4000/api

### Register
POST {{API}}/register
Content-Type: application/json

{
    "email": "",
    "password": "",
    "confirm": "",
    "firstname": "",
    "lastname": "",
    "phone": ""
}

### Login
POST {{API}}/login
Content-Type: application/json

{
    "email": "admincoder@coder.com",
    "password": "adminCod3r123"
}

### Forgot Password
POST {{API}}/users
Content-Type: application/json

{
    "email": "admincoder@coder.com"
}

### Recover Password
PUT {{API}}/users/admincoder@coder.com
Content-Type: application/json
Authorization: Bearer 

{
    "password": ""
}